### PR TITLE
AD_HDF5_SINGLE: return sliceable object

### PR DESCRIPTION
**Pull request by prjemian**
- #31

### CODE REVIEW

**Comment by prjemian** [comment]
The CI failure is because the conf.py file is out of date with current Sphinx.  (need to comment the `language=` line now, the default is acceptable).

**Comment by danielballan** [comment]
I am slightly worried this API change could break other uses of `AD_HDF5_SINGLE`. Would it be better to make a new handler (and new `spec` name) with the new behavior? Or is this actually a bug, @tacaswell?

**Comment by tacaswell** [comment]
I think this is actually a bug and I think this change is mostly backwards compatible (what would you be doing to a list that a N-D stack of numpy arrays would not handle?).

I am in favor of merging this but making sure the SXSS AST is very aware of this.

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
This may also fix a latent bug that we have not hit at SIX.

**Comment by prjemian** [comment]
Here's my notebook that relies on this change: https://github.com/BCDA-APS/apstools/blob/691-AD-HDF5-Single-mode/docs/source/examples/de_2_adsim_hdf5_single_mode.ipynb

**Comment by prjemian** [comment]
@tacaswell - Thanks for the review, and the fix code (that's yours).  @danielballan - Thanks for the merge.

**Comment by danielballan** [comment]
Released https://pypi.org/project/area-detector-handlers/0.0.10/

**Pull request merged**
